/*
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy at
 * https://opensource.org/license/cpal-1.0. The Original Code is VoidCat Harness. The Initial Developer is
 * iamnotnotacat. Copyright (c) 2026 iamnotnotacat. All Rights Reserved. Software is provided "AS IS",
 * without warranty. See LICENSE and NOTICE for details and attribution requirements.
 */
import assert from "node:assert/strict";
import test from "node:test";
import { HUNTER_BUILT_IN_PRESETS, HUNTER_SOURCE_CATEGORIES, HUNTER_SOURCE_DEFINITIONS, applyHunterPreset, filterHunterSources, mergeHunterSourceDefinitions, migrateHunterWorkspaceSettings, sourceCategoryCheckState } from "../build/hunter-seeker/source-workspace.ts";

test("all catalog sources receive one real category and tailored schema", () => { assert.equal(HUNTER_SOURCE_DEFINITIONS.length, 41); assert.equal(new Set(HUNTER_SOURCE_DEFINITIONS.map(({ id }) => id)).size, 41); for (const definition of HUNTER_SOURCE_DEFINITIONS) { assert.ok(HUNTER_SOURCE_CATEGORIES.some(({ id }) => id === definition.category), definition.id); assert.ok(definition.settingsSchema.some(({ section }) => section === "policy"), definition.id); if (definition.capabilities.geometryTypes.some((type) => type !== "catalog")) assert.ok(definition.settingsSchema.some(({ section }) => section === "display"), definition.id); if (definition.capabilities.supportsCredentials) assert.ok(definition.settingsSchema.some(({ type }) => type === "secret"), definition.id); } });
test("legacy operational descriptors merge without duplicating mapped sources", () => { const definitions = mergeHunterSourceDefinitions([{ id: "adsb.lol.military", displayName: "ADSB Military", category: "aviation", providerDocsUrl: "https://example.test/adsb", pollCadenceMs: 120000, credentialType: "none" }, { id: "usgs.earthquakes", displayName: "USGS Earthquakes", category: "seismic", providerDocsUrl: "https://example.test/usgs", pollCadenceMs: 120000, credentialType: "none" }]); assert.equal(definitions.filter(({ id }) => id === "adsb.lol").length, 1); assert.deepEqual(definitions.find(({ id }) => id === "adsb.lol")?.runtimeSourceIds, ["adsb.lol.military"]); assert.equal(definitions.find(({ id }) => id === "usgs.earthquakes")?.category, "natural-hazards"); });
test("the 41-source catalog joins original runtime sources without duplicate live adapters", () => { const runtime = [{ id: "adsb.lol.military", displayName: "ADSB Military" }, { id: "opensky.civil-airspace", displayName: "OpenSky Civil" }, { id: "nasa.eonet.events", displayName: "NASA EONET" }, { id: "gdacs.events", displayName: "GDACS" }, { id: "noaa.nhc", displayName: "NHC" }, { id: "aviationweather.hazards", displayName: "Aviation Weather" }, { id: "gdelt.geo2", displayName: "GDELT GEO" }, { id: "usgs.earthquakes", displayName: "USGS" }].map((item) => ({ ...item, category: "test", providerDocsUrl: "https://example.test", pollCadenceMs: 120000, credentialType: "none" })); const definitions = mergeHunterSourceDefinitions(runtime); assert.equal(HUNTER_SOURCE_DEFINITIONS.length, 41); assert.equal(definitions.length, 42); assert.equal(new Set(definitions.map(({ id }) => id)).size, definitions.length); assert.deepEqual(definitions.find(({ id }) => id === "adsb.lol")?.runtimeSourceIds, ["adsb.lol.military", "opensky.civil-airspace"]); assert.deepEqual(definitions.find(({ id }) => id === "nasa.eonet")?.runtimeSourceIds, ["nasa.eonet.events"]); });
test("workspace migration preserves old toggles and clamps unsafe values", () => { const workspace = migrateHunterWorkspaceSettings({ explorerWidth: 900, sourcePreferences: { "adsb.lol": { opacity: -5, markerSize: 99 } } }, { "adsb.lol.military": { enabled: true } }); assert.equal(workspace.version, 2); assert.equal(workspace.explorerWidth, 480); assert.equal(workspace.sourcePreferences["adsb.lol"].enabled, true); assert.equal(workspace.sourcePreferences["adsb.lol"].opacity, .1); assert.equal(workspace.sourcePreferences["adsb.lol"].markerSize, 2); });
test("query refresh settings are persisted and bounded by safe traffic limits", () => { const definition = HUNTER_SOURCE_DEFINITIONS.find((source) => source.id === "openmeteo.weather"); assert.ok(definition); const migrated = migrateHunterWorkspaceSettings({ sourcePreferences: { "openmeteo.weather": { automaticRefresh: true, refreshIntervalSeconds: 1, requestBudgetPercent: 1 } } }); const preference = migrated.sourcePreferences[definition.id]; assert.equal(preference.automaticRefresh, true); assert.equal(preference.refreshIntervalSeconds, 30); assert.equal(preference.requestBudgetPercent, 10); });
test("category state is truly three-state and excludes ineligible sources", () => { const definitions = HUNTER_SOURCE_DEFINITIONS.filter(({ category }) => category === "conflict"); let workspace = migrateHunterWorkspaceSettings(null); assert.equal(sourceCategoryCheckState(definitions, workspace), "unchecked"); workspace = { ...workspace, sourcePreferences: { ...workspace.sourcePreferences, [definitions[0].id]: { ...workspace.sourcePreferences[definitions[0].id], enabled: true } } }; assert.equal(sourceCategoryCheckState(definitions, workspace), "indeterminate"); assert.equal(sourceCategoryCheckState(definitions, workspace, (definition) => definition.id === definitions[0].id), "checked"); });
test("search covers provider, category, description, geometry, and render modes", () => { assert.ok(filterHunterSources(HUNTER_SOURCE_DEFINITIONS, "cyber").some(({ id }) => id === "ripe.stat")); assert.ok(filterHunterSources(HUNTER_SOURCE_DEFINITIONS, "raster").some(({ id }) => id === "noaa.nowcoast")); assert.ok(filterHunterSources(HUNTER_SOURCE_DEFINITIONS, "airnowapi").some(({ id }) => id === "epa.airnow")); });
test("built-in presets keep retrieval and map visibility separate", () => { const minimal = HUNTER_BUILT_IN_PRESETS.find(({ id }) => id === "minimal-map")!; const workspace = applyHunterPreset(migrateHunterWorkspaceSettings(null), minimal); assert.equal(Object.values(workspace.sourcePreferences).some(({ enabled }) => enabled), false); assert.equal(Object.values(workspace.sourcePreferences).some(({ layerVisible }) => layerVisible), false); const weather = applyHunterPreset(workspace, HUNTER_BUILT_IN_PRESETS.find(({ id }) => id === "severe-weather")!); assert.ok(HUNTER_SOURCE_DEFINITIONS.filter(({ category }) => category === "weather").every(({ id }) => weather.sourcePreferences[id].enabled && weather.sourcePreferences[id].layerVisible)); });
test("custom presets safely restore source filters and display settings", () => { const initial = migrateHunterWorkspaceSettings(null); const source = HUNTER_SOURCE_DEFINITIONS[0]; const changed = { ...initial.sourcePreferences[source.id], enabled: true, layerVisible: true, opacity: .4, labels: true, minimumZoom: 3, maximumZoom: 9, filters: { minimumSeverity: .75 } }; const preset = { id: "operator-view", name: "Operator View", sourceIds: [source.id], visibleSourceIds: [source.id], map: { longitude: 12, latitude: 34, zoom: 7 }, timeWindowHours: 6, sourcePreferences: { [source.id]: changed } }; const imported = migrateHunterWorkspaceSettings({ customPresets: [preset] }); const restored = applyHunterPreset(initial, imported.customPresets[0]); assert.equal(restored.sourcePreferences[source.id].opacity, .4); assert.equal(restored.sourcePreferences[source.id].labels, true); assert.deepEqual(restored.sourcePreferences[source.id].filters, { minimumSeverity: .75 }); assert.equal(imported.customPresets[0].map.zoom, 7); });
test("settings schema exposes only enforced controls", () => { const definition = HUNTER_SOURCE_DEFINITIONS.find(({ capabilities }) => capabilities.geometryTypes.some((type) => type !== "catalog"))!; const fieldIds = new Set(definition.settingsSchema.map(({ id }) => id)); assert.equal(fieldIds.has("requestTimeoutSeconds"), false); assert.equal(fieldIds.has("retryCount"), false); assert.equal(fieldIds.has("includeInCorrelation"), false); assert.equal(fieldIds.has("notifications"), false); assert.equal(fieldIds.has("minimumZoom"), true); assert.equal(fieldIds.has("maximumZoom"), true); });
