"use client";

import { useEffect, useRef, useState } from "react";
import type { VoidCatSettings } from "./WebPanel";
import { useNotifications } from "./NotificationCenter";

export function AppSettingsPanel({ settings, onSave, onRefresh, onModelRescan }: { settings: VoidCatSettings; onSave: (value: Partial<VoidCatSettings>) => Promise<void>; onRefresh: () => Promise<void>; onModelRescan: () => Promise<void> }) {
  const { notify } = useNotifications(); const importRef = useRef<HTMLInputElement | null>(null); const [voice, setVoice] = useState<VoiceDesktopStatus | null>(null); const [lan, setLan] = useState<LanDesktopStatus | null>(null); const [modelLibrary, setModelLibrary] = useState<ModelLibraryDesktopStatus | null>(null); const [busy, setBusy] = useState("");
  useEffect(() => { if (!window.voidcatDesktop) return; void Promise.all([window.voidcatDesktop.voice.status(), window.voidcatDesktop.lan.status(), window.voidcatDesktop.models.status()]).then(([voiceStatus, lanStatus, modelStatus]) => { setVoice(voiceStatus); setLan(lanStatus); setModelLibrary(modelStatus); }); }, []);
  useEffect(() => { if (!modelLibrary?.scan.active || !window.voidcatDesktop) return; const timer = window.setInterval(() => { void window.voidcatDesktop?.models.status().then(setModelLibrary); }, 500); return () => window.clearInterval(timer); }, [modelLibrary?.scan.active]);
  async function backup() { setBusy("backup"); try { const response = await fetch("/api/backups", { method: "POST" }); const data = await response.json() as { directory?: string; error?: string }; if (!response.ok) throw new Error(data.error ?? "Backup failed."); notify({ tone: "success", title: "Validated backup created", message: data.directory ?? "Backup completed." }); } catch (error) { notify({ tone: "error", title: "Backup failed", message: error instanceof Error ? error.message : "Backup failed." }); } finally { setBusy(""); } }
  async function exportProject() { const response = await fetch("/api/projects/export"); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Export failed."); const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `voidcat-project-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); }
  async function importProject(file: File) { if (file.size > 10 * 1024 * 1024) throw new Error("Project imports are capped at 10 MB."); const data = JSON.parse(await file.text()); const response = await fetch("/api/projects/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "Import failed."); await onRefresh(); notify({ tone: "success", title: "Project imported", message: "The imported records were placed in a new persistent project." }); }
  async function toggleLan() { if (!window.voidcatDesktop) return; const result = await window.voidcatDesktop.lan.configure(!lan?.enabled); setLan(result); }
  async function choosePrimaryModelFolder() { if (!window.voidcatDesktop) return; setModelLibrary(await window.voidcatDesktop.models.choosePrimaryFolder()); }
  async function addModelScanFolder() { if (!window.voidcatDesktop) return; setModelLibrary(await window.voidcatDesktop.models.chooseScanFolder()); }
  async function removeModelScanFolder(folder: string) { if (!window.voidcatDesktop) return; setModelLibrary(await window.voidcatDesktop.models.removeScanFolder(folder)); }
  async function runModelScan(mode: "targeted" | "full", root?: string) {
    if (!window.voidcatDesktop || modelLibrary?.scan.active) return;
    if (mode === "full" && !window.confirm("Run a bounded scan of all accessible local drives? This can take several minutes. VoidCat skips system-heavy folders, yields between batches, and can be cancelled.")) return;
    setBusy("model-scan");
    try { const operation = window.voidcatDesktop.models.scan({ mode, root }); setModelLibrary(await window.voidcatDesktop.models.status()); const result = await operation; setModelLibrary(result); await onModelRescan(); notify({ tone: result.scan.cancelled ? "info" : "success", title: result.scan.cancelled ? "Model scan cancelled" : "UNIT discovery complete", message: `${result.compatibleModels} compatible GGUF UNIT(s) are indexed for the Unit Bank.` }); }
    catch (error) { notify({ tone: "error", title: "Model scan failed safely", message: error instanceof Error ? error.message : "The model scan failed." }); setModelLibrary(await window.voidcatDesktop.models.status()); }
    finally { setBusy(""); }
  }
  async function cancelModelScan() { if (!window.voidcatDesktop) return; await window.voidcatDesktop.models.cancelScan(); }
  return <section className="phase-panel app-settings-panel"><div className="phase-heading"><div><p className="kicker">APPLICATION POLICY {"//"} LOCAL CONTROL</p><h2>APP SETTINGS</h2></div><span className="phase-counter">PRIVACY FIRST</span></div><div className="settings-cards">
    <article className="model-library-settings"><header><span>LOCAL MODEL STORAGE + DISCOVERY</span><b>{modelLibrary?.scan.active ? "SCAN ACTIVE" : `${modelLibrary?.compatibleModels ?? 0} DISCOVERED`}</b></header><div className="model-folder-primary"><span>PRIMARY STORAGE / DOWNLOAD FOLDER</span><code title={modelLibrary?.primaryFolder}>{modelLibrary?.primaryFolder ?? "DESKTOP APP REQUIRED"}</code><button onClick={() => void choosePrimaryModelFolder()} disabled={!window.voidcatDesktop || Boolean(modelLibrary?.scan.active)}>CHOOSE FOLDER</button></div><div className="model-scan-actions"><button onClick={() => void addModelScanFolder()} disabled={!window.voidcatDesktop || Boolean(modelLibrary?.scan.active)}>ADD TARGET FOLDER</button><button onClick={() => void runModelScan("targeted", modelLibrary?.primaryFolder)} disabled={!modelLibrary?.primaryFolder || Boolean(modelLibrary?.scan.active)}>SCAN PRIMARY</button><button className="full-scan" onClick={() => void runModelScan("full")} disabled={!window.voidcatDesktop || Boolean(modelLibrary?.scan.active)}>FULL SYSTEM SCAN</button>{modelLibrary?.scan.active && <button className="cancel-action" onClick={() => void cancelModelScan()}>CANCEL SCAN</button>}</div>{modelLibrary?.scan.active && <div className="model-scan-progress" role="status" aria-live="polite"><strong>{modelLibrary.scan.mode?.toUpperCase()} SCAN // {modelLibrary.scan.modelsFound ?? 0} GGUF FOUND</strong><span>{modelLibrary.scan.directoriesScanned ?? 0} folders // {modelLibrary.scan.filesScanned ?? 0} files</span><code title={modelLibrary.scan.currentPath}>{modelLibrary.scan.currentPath}</code></div>}<div className="model-scan-folders">{modelLibrary?.scanFolders.map((folder) => <div key={folder}><code title={folder}>{folder}</code><button onClick={() => void runModelScan("targeted", folder)} disabled={Boolean(modelLibrary.scan.active)}>SCAN</button><button aria-label={`Remove scan folder ${folder}`} onClick={() => void removeModelScanFolder(folder)} disabled={Boolean(modelLibrary.scan.active)}>REMOVE</button></div>)}</div>{modelLibrary?.scan.error && <p className="runtime-error">{modelLibrary.scan.error}</p>}<p>Targeted scans inspect only folders you select. Full scans are operator-confirmed, bounded, cancellable, and skip symlinks and system-heavy directories. Compatible GGUF files remain where they are and are linked into the local runtime only when you initialize them.</p></article>
    <article><header><span>VOICE SYSTEM</span><b>{voice?.transcriptionAvailable ? "LOCAL WHISPER READY" : "SETUP REQUIRED"}</b></header><div className="settings-grid"><label>INPUT MODE<select value={settings.voiceInputMode} onChange={(event) => void onSave({ voiceInputMode: event.target.value as "push" | "toggle" })}><option value="push">PUSH-TO-TALK</option><option value="toggle">TOGGLE-TO-TALK</option></select></label><label>VOICE PROFILE<select value={settings.voiceProfile} onChange={(event) => void onSave({ voiceProfile: event.target.value as VoiceProfile })}><option value="computer-male">COMPUTERIZED MALE</option><option value="computer-female">COMPUTERIZED FEMALE</option><option value="tactical-commander">TACTICAL COMMANDER // ORIGINAL</option><option value="high-energy-pilot">HIGH-ENERGY PILOT // ORIGINAL</option></select></label><label>SPEAKING SPEED<input type="range" min="0.5" max="2" step="0.1" value={settings.voiceSpeed} onChange={(event) => void onSave({ voiceSpeed: Number(event.target.value) })} /><small>{settings.voiceSpeed.toFixed(1)}×</small></label><label className="switch-setting"><input type="checkbox" checked={settings.spokenResponses} onChange={(event) => void onSave({ spokenResponses: event.target.checked })} /><span>SPEAK UNIT RESPONSES</span></label></div><div className="voice-setup"><button onClick={() => void window.voidcatDesktop?.voice.chooseExecutable().then(setVoice)}>CHOOSE WHISPER.CPP</button><button onClick={() => void window.voidcatDesktop?.voice.chooseModel().then(setVoice)}>CHOOSE LOCAL MODEL</button><button onClick={() => void window.voidcatDesktop?.voice.speak({ text: "VoidCat local voice link ready.", profile: settings.voiceProfile, speed: settings.voiceSpeed })}>TEST VOICE</button><small>{voice?.executableName ?? "NO EXECUTABLE"} {"//"} {voice?.modelName ?? "NO MODEL"}</small></div><p>Microphone audio and speech remain on this computer. Push/toggle capture is capped at two minutes and local Whisper files are deleted after transcription.</p></article>
    <article><header><span>BACKUP + PORTABILITY</span><b>BOUNDED OPERATIONS</b></header><div className="settings-actions"><button onClick={() => void backup()} disabled={Boolean(busy)}>{busy === "backup" ? "VALIDATING..." : "CREATE VALIDATED BACKUP"}</button><button onClick={() => void exportProject()}>EXPORT ACTIVE PROJECT</button><button onClick={() => importRef.current?.click()}>IMPORT AS NEW PROJECT</button><input ref={importRef} type="file" accept="application/json,.json" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void importProject(file).catch((error) => notify({ tone: "error", title: "Import failed", message: error instanceof Error ? error.message : "Import failed." })); event.target.value = ""; }} /></div><p>Backups copy and validate the SQLite database set. Project imports never overwrite an existing project.</p></article>
    <article><header><span>OPTIONAL LAN ACCESS</span><b>{lan?.enabled ? "AUTHENTICATED" : "LOCALHOST ONLY"}</b></header><div className="settings-actions"><button onClick={() => void toggleLan()}>{lan?.enabled ? "DISABLE LAN ACCESS" : "ENABLE AUTHENTICATED LAN"}</button>{lan?.urls[0] && <button onClick={() => void navigator.clipboard.writeText(lan.urls[0])}>COPY AUTHENTICATED LINK</button>}</div>{lan?.urls.map((url) => <code key={url}>{url.replace(/voidcat_token=.*/, "voidcat_token=[HIDDEN]")}</code>)}{lan?.restartRequired && <strong className="restart-warning">RESTART VOIDCAT TO APPLY THIS NETWORK CHANGE</strong>}<p>LAN access is off by default. Remote requests require the protected token, but this is plain HTTP—not encryption. Use it only on a trusted private network.</p></article>
    <article className="privacy-contract"><header><span>DEFAULT PRIVACY CONTRACT</span><b>INSPECTABLE + REMOVABLE</b></header><ul><li>Chats, approved memories, embeddings, documents, and projects remain local.</li><li>Only explicit searches, feed pulls, and enabled external UNIT tools leave this computer.</li><li>Search providers receive the bounded query—not the full conversation.</li><li>Voice is local unless you deliberately replace the local engine later.</li><li>External capabilities are marked in the Command feature matrix and News Watch.</li><li>Retrieved context and approved memories remain visible and removable.</li></ul></article>
  </div></section>;
}
