import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useNotifications } from "./NotificationCenter";

type WatchlistKind = "aircraft-icao" | "aircraft-callsign" | "aircraft-tail" | "vessel-mmsi" | "satellite-norad" | "geofence";
type WatchlistRule = { id: string; kind: WatchlistKind; label: string; value: string | null; geometry: { type: string; latitude?: number; longitude?: number; radiusKm?: number } | null; enabled: boolean; updatedAt: string };
type TriggerEvent = { id: string; triggerType: string; title: string; message: string; occurredAt: string; observationId: string; acknowledged: boolean };
type HealthSample = { sourceId: string; at: string; status: string; errorRate: number; recordsPerHour: number; expectedBaseline: number; silentZero: boolean; aiContextEligible: boolean; message: string };
type ReplayManifest = { id: string; label: string; createdAt: string; endsAt: string; completedAt: string | null; recordCount: number; bytes: number; status: string; sourceIds: string[] };

function formatBytes(bytes: number) { return bytes < 1024 ** 2 ? `${Math.round(bytes / 1024)} KiB` : `${(bytes / 1024 ** 2).toFixed(1)} MiB`; }
function formatTime(value: string) { return new Date(value).toLocaleString([], { month: "short", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit" }); }

export function HunterStageFivePanel({ sourceIds, onClose, onReplayLoaded, onReplayExit }: {
  sourceIds: string[];
  onClose: () => void;
  onReplayLoaded: (observations: unknown[], manifest: ReplayManifest) => void;
  onReplayExit: () => void;
}) {
  const { notify } = useNotifications();
  const [tab, setTab] = useState<"watchlists" | "triggers" | "health" | "replay">("watchlists");
  const [rules, setRules] = useState<WatchlistRule[]>([]); const [triggers, setTriggers] = useState<TriggerEvent[]>([]); const [health, setHealth] = useState<HealthSample[]>([]); const [replays, setReplays] = useState<ReplayManifest[]>([]); const [activeReplay, setActiveReplay] = useState<ReplayManifest | null>(null);
  const [healthSource, setHealthSource] = useState("all");
  const [kind, setKind] = useState<WatchlistKind>("aircraft-icao"); const [label, setLabel] = useState(""); const [value, setValue] = useState(""); const [latitude, setLatitude] = useState(0); const [longitude, setLongitude] = useState(0); const [radiusKm, setRadiusKm] = useState(25); const [durationMs, setDurationMs] = useState(5 * 60_000); const [busy, setBusy] = useState(false);
  const importRef = useRef<HTMLInputElement | null>(null);

  const load = useCallback(async () => {
    const [watchlistResponse, triggerResponse, healthResponse, replayResponse] = await Promise.all([fetch("/api/hunter-seeker/watchlists"), fetch("/api/hunter-seeker/triggers"), fetch("/api/hunter-seeker/health/history"), fetch("/api/hunter-seeker/replays")]);
    const [watchlistData, triggerData, healthData, replayData] = await Promise.all([watchlistResponse.json(), triggerResponse.json(), healthResponse.json(), replayResponse.json()]) as Array<Record<string, unknown>>;
    if (!watchlistResponse.ok || !triggerResponse.ok || !healthResponse.ok || !replayResponse.ok) throw new Error(String(watchlistData.error ?? triggerData.error ?? healthData.error ?? replayData.error ?? "Stage 5 status could not be loaded."));
    setRules((watchlistData.rules as WatchlistRule[]) ?? []); setTriggers((triggerData.events as TriggerEvent[]) ?? []); setHealth((healthData.samples as HealthSample[]) ?? []); setReplays((replayData.replays as ReplayManifest[]) ?? []); setActiveReplay((replayData.active as ReplayManifest | null) ?? null);
  }, []);
  useEffect(() => {
    const refresh = () => void load().catch((error) => notify({ tone: "error", title: "Stage 5 status unavailable", message: error instanceof Error ? error.message : "Stage 5 status could not be loaded." }));
    const initial = window.setTimeout(refresh, 0); const timer = window.setInterval(refresh, 10_000);
    return () => { window.clearTimeout(initial); window.clearInterval(timer); };
  }, [load, notify]);

  async function request(url: string, method: string, body?: unknown) {
    const response = await fetch(url, { method, headers: body === undefined ? undefined : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "Stage 5 operation failed."); return data;
  }
  async function addRule() {
    setBusy(true); try { await request("/api/hunter-seeker/watchlists", "POST", { kind, label, ...(kind === "geofence" ? { geometry: { type: "circle", latitude, longitude, radiusKm } } : { value }) }); setLabel(""); setValue(""); await load(); notify({ tone: "success", title: "Target rule saved", message: "Matching observations will be protected and evaluated by the trigger engine." }); } catch (error) { notify({ tone: "error", title: "Rule not saved", message: error instanceof Error ? error.message : "Rule not saved." }); } finally { setBusy(false); }
  }
  async function toggleRule(rule: WatchlistRule) { await request(`/api/hunter-seeker/watchlists/${encodeURIComponent(rule.id)}`, "PATCH", { enabled: !rule.enabled }); await load(); }
  async function deleteRule(rule: WatchlistRule) { if (!window.confirm(`Delete watchlist rule “${rule.label}”? Existing protected history and trigger evidence will remain.`)) return; await request(`/api/hunter-seeker/watchlists/${encodeURIComponent(rule.id)}`, "DELETE"); await load(); }
  async function exportRules() { const response = await fetch("/api/hunter-seeker/watchlists/export"); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Export failed."); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); link.download = `voidcat-watchlists-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); }
  async function importRules(file: File) { const text = await file.text(); if (text.length > 2_000_000) throw new Error("Watchlist import exceeds 2 MB."); await request("/api/hunter-seeker/watchlists/import", "POST", JSON.parse(text)); await load(); }
  async function startReplay() { setBusy(true); try { await request("/api/hunter-seeker/replays", "POST", { durationMs, sourceIds, label: `Situation window ${new Date().toLocaleString()}` }); await load(); notify({ tone: "success", title: "Replay recording started", message: "Future normalized observations will be written to a bounded JSONL window." }); } finally { setBusy(false); } }
  async function stopReplay() { setBusy(true); try { await request("/api/hunter-seeker/replays/stop", "POST"); await load(); } finally { setBusy(false); } }
  async function playReplay(manifest: ReplayManifest) { setBusy(true); try { const response = await fetch(`/api/hunter-seeker/replays/${encodeURIComponent(manifest.id)}/load`, { method: "POST" }); const data = await response.json() as { observations?: unknown[]; manifest?: ReplayManifest; error?: string }; if (!response.ok || !data.manifest) throw new Error(data.error ?? "Replay could not be loaded."); onReplayLoaded(data.observations ?? [], data.manifest); notify({ tone: "success", title: "Offline replay loaded", message: `${(data.observations ?? []).length.toLocaleString()} recorded observations loaded without provider requests.` }); } finally { setBusy(false); } }

  const latestHealth = useMemo(() => {
    const latest = new Map<string, HealthSample>();
    for (const sample of health) if (!latest.has(sample.sourceId)) latest.set(sample.sourceId, sample);
    return [...latest.values()];
  }, [health]);
  const healthSources = useMemo(() => [...new Set(health.map((sample) => sample.sourceId))].sort(), [health]);
  const healthTimeline = useMemo(() => health.filter((sample) => healthSource === "all" || sample.sourceId === healthSource).slice(0, 200), [health, healthSource]);
  return <div className="hunter-stage-five-backdrop" role="presentation" onMouseDown={onClose}><section className="hunter-stage-five-dialog" role="dialog" aria-modal="true" aria-label="Hunter-Seeker targeting, triggers, health, and replay" onMouseDown={(event) => event.stopPropagation()}>
    <header><div><span>STAGE 05 // BEYOND NOWCAST</span><strong>TARGETING & REPLAY CONTROL</strong></div><button aria-label="Close Stage 5 controls" onClick={onClose}>×</button></header>
    <nav>{(["watchlists", "triggers", "health", "replay"] as const).map((name) => <button className={tab === name ? "active" : ""} key={name} onClick={() => setTab(name)}>{name.toUpperCase()}</button>)}</nav>
    <div className="hunter-stage-five-content">
      {tab === "watchlists" && <section className="hunter-watchlist-manager"><div className="hunter-stage-five-form"><label>TYPE<select value={kind} onChange={(event) => setKind(event.target.value as WatchlistKind)}><option value="aircraft-icao">AIRCRAFT ICAO</option><option value="aircraft-callsign">AIRCRAFT CALLSIGN</option><option value="aircraft-tail">AIRCRAFT TAIL NUMBER</option><option value="vessel-mmsi">VESSEL MMSI</option><option value="satellite-norad">SATELLITE NORAD ID</option><option value="geofence">GEOGRAPHIC AREA</option></select></label><label>LABEL<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Priority contact" /></label>{kind === "geofence" ? <><label>LATITUDE<input type="number" min={-90} max={90} value={latitude} onChange={(event) => setLatitude(Number(event.target.value))} /></label><label>LONGITUDE<input type="number" min={-180} max={180} value={longitude} onChange={(event) => setLongitude(Number(event.target.value))} /></label><label>RADIUS KM<input type="number" min={1} max={2000} value={radiusKm} onChange={(event) => setRadiusKm(Number(event.target.value))} /></label></> : <label>IDENTIFIER<input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Exact identifier" /></label>}<button className="primary-action" disabled={busy || !label.trim() || (kind !== "geofence" && !value.trim())} onClick={() => void addRule()}>ADD RULE</button></div><div className="hunter-stage-five-tools"><button onClick={() => void exportRules()}>EXPORT JSON</button><button onClick={() => importRef.current?.click()}>IMPORT JSON</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importRules(file).catch((error) => notify({ tone: "error", title: "Import failed", message: error instanceof Error ? error.message : "Import failed." })); event.target.value = ""; }} /></div><div className="hunter-watchlist-list">{rules.map((rule) => <article key={rule.id}><b>{rule.kind.toUpperCase()}</b><div><strong>{rule.label}</strong><small>{rule.value ?? (rule.geometry?.type === "circle" ? `${rule.geometry.latitude?.toFixed(3)}, ${rule.geometry.longitude?.toFixed(3)} // ${rule.geometry.radiusKm} KM` : "GEOGRAPHIC AREA")}</small></div><button className={rule.enabled ? "active" : ""} onClick={() => void toggleRule(rule)}>{rule.enabled ? "ARMED" : "OFF"}</button><button onClick={() => void deleteRule(rule)}>DELETE</button></article>)}{!rules.length && <p>NO TARGET RULES // ADD AN IDENTIFIER OR GEOGRAPHIC AREA</p>}</div></section>}
      {tab === "triggers" && <section className="hunter-trigger-log">{triggers.map((event) => <article className={event.acknowledged ? "acknowledged" : ""} key={event.id}><b>{event.triggerType.replaceAll("-", " ").toUpperCase()}</b><div><strong>{event.title}</strong><p>{event.message}</p><small>{formatTime(event.occurredAt)} // OBS {event.observationId}</small></div>{!event.acknowledged && <button onClick={() => void request(`/api/hunter-seeker/triggers/${encodeURIComponent(event.id)}`, "PATCH").then(load)}>ACK</button>}</article>)}{!triggers.length && <p>NO TRIGGERS RECORDED</p>}</section>}
      {tab === "health" && <section className="hunter-health-history"><div className="hunter-health-current">{latestHealth.map((sample) => <article className={sample.aiContextEligible ? "healthy" : "excluded"} key={sample.sourceId}><header><strong>{sample.sourceId}</strong><b>{sample.aiContextEligible ? "AI ELIGIBLE" : "EXCLUDED"}</b></header><dl><div><dt>ERROR RATE</dt><dd>{Math.round(sample.errorRate * 100)}%</dd></div><div><dt>RECORDS / HR</dt><dd>{Math.round(sample.recordsPerHour)}</dd></div><div><dt>BASELINE</dt><dd>{sample.expectedBaseline.toFixed(1)}</dd></div><div><dt>SILENT ZERO</dt><dd>{sample.silentZero ? "YES" : "NO"}</dd></div></dl><p>{sample.message}</p><small>{formatTime(sample.at)} // {sample.status.toUpperCase()}</small></article>)}{!latestHealth.length && <p>HEALTH HISTORY ACQUIRING // SAMPLES ARE WRITTEN EVERY FIVE MINUTES</p>}</div><div className="hunter-health-timeline"><header><div><span>30-DAY HEALTH HISTORY</span><strong>{healthTimeline.length} RECENT SAMPLES</strong></div><label>SOURCE<select value={healthSource} onChange={(event) => setHealthSource(event.target.value)}><option value="all">ALL SOURCES</option>{healthSources.map((sourceId) => <option value={sourceId} key={sourceId}>{sourceId}</option>)}</select></label></header><div>{healthTimeline.map((sample, index) => <article className={sample.aiContextEligible ? "eligible" : "excluded"} key={`${sample.sourceId}:${sample.at}:${index}`}><time>{formatTime(sample.at)}</time><strong>{sample.sourceId}</strong><b>{sample.status.toUpperCase()}</b><span>ERR {Math.round(sample.errorRate * 100)}%</span><span>{Math.round(sample.recordsPerHour)} REC/HR</span><span>BASE {sample.expectedBaseline.toFixed(1)}</span><span>{sample.silentZero ? "SILENT ZERO" : sample.aiContextEligible ? "AI ELIGIBLE" : "AI EXCLUDED"}</span></article>)}</div></div></section>}
      {tab === "replay" && <section className="hunter-replay-manager"><div className="hunter-replay-controls"><label>WINDOW<select value={durationMs} onChange={(event) => setDurationMs(Number(event.target.value))}><option value={60_000}>1 MINUTE</option><option value={5 * 60_000}>5 MINUTES</option><option value={15 * 60_000}>15 MINUTES</option><option value={30 * 60_000}>30 MINUTES</option></select></label>{activeReplay ? <button className="cancel-action" disabled={busy} onClick={() => void stopReplay()}>STOP RECORDING</button> : <button className="primary-action" disabled={busy} onClick={() => void startReplay()}>RECORD LIVE WINDOW</button>}<button onClick={onReplayExit}>RETURN TO LIVE</button>{activeReplay && <span>RECORDING // {activeReplay.recordCount} RECORDS // ENDS {formatTime(activeReplay.endsAt)}</span>}</div><div className="hunter-replay-list">{replays.map((replay) => <article key={replay.id}><b>{replay.status.toUpperCase()}</b><div><strong>{replay.label}</strong><small>{formatTime(replay.createdAt)} // {replay.recordCount.toLocaleString()} RECORDS // {formatBytes(replay.bytes)}</small></div><button disabled={replay.status !== "complete" || busy} onClick={() => void playReplay(replay)}>PLAY OFFLINE</button></article>)}{!replays.length && <p>NO REPLAY WINDOWS RECORDED</p>}</div></section>}
    </div>
  </section></div>;
}
