/*
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy at
 * https://opensource.org/license/cpal-1.0. The Original Code is VoidCat Harness. The Initial Developer is
 * iamnotnotacat. Copyright (c) 2026 iamnotnotacat. All Rights Reserved. Software is provided "AS IS",
 * without warranty. See LICENSE and NOTICE for details and attribution requirements.
 */
import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import { useNotifications } from "./NotificationCenter";
import type { HunterOsintDraft } from "./osint-hunter-types";
import type { Provider } from "./OsintProviderPanel";

type Budget = { maximumProviders: number; maximumExternalCalls: number; maximumRuntimeMs: number; maximumEntities: number; maximumEvidenceBytes: number; maximumDiscoveryDepth: number };
type Plan = { id: string; steps: Array<{ id: string; order: number; providerId: string; capabilityId: string; purpose: string }>; reservations: { providers: number; externalCalls: number; maximumEvidenceBytes: number; maximumEntities: number; maximumDiscoveryDepth: number }; execution: { ordering: string; followCandidateLeadsAutomatically: boolean } };
type Preview = { investigationId: string; seed: { type: string; value: string; label?: string }; objective: string; authorizationMode: string; budget: Budget; policyDecision: { outcome: string; reasons: string[] }; plan: Plan | null; providerIds: string[]; warnings: string[]; sensitive: boolean };
type InvestigationSummary = { id: string; seed: { type: string; value: string; label?: string }; objective: string; authorizationMode: string; status: string; budget: Budget; planId?: string; counts: { providers: number; externalCalls: number; entities: number; evidenceBytes: number; leads: number }; warnings: string[]; createdAt: string; updatedAt: string; completedAt?: string };
type InvestigationDetail = {
  investigation: InvestigationSummary;
  entities: Array<{ id: string; type: string; displayName: string; identifiers: Array<{ type: string; normalizedValue: string; confidence: number; evidenceIds: string[] }> }>;
  evidence: Array<{ id: string; providerId: string; sourceRef: string; retrievedAt: string; observedAt?: string; title: string; excerpt?: string; url?: string; sensitivity: string; byteLength: number; cache: { status: string; ageMs: number; expiresAt?: string }; attribution: { provider?: string; termsUrl?: string } }>;
  observations: Array<{ id: string; entityId: string; providerId: string; confidence: number; confidenceCategory: string; directness: string; freshness: string; coverageLimitations: string[]; evidenceIds: string[] }>;
  claims: Array<{ id: string; subjectEntityId: string; predicate: string; value: unknown; status: string; confidence: number; confidenceCategory: string; explanation: string; evidenceIds: string[]; observationIds: string[] }>;
  conclusions: Array<{ claimId: string; statement: string; supportingEvidenceIds: string[]; contradictingEvidenceIds: string[]; confidence: { score: number; category: string; explanation: string }; freshness: { category: string }; coverageLimitations: string[] }>;
  relationships: Array<{ id: string; sourceEntityId: string; targetEntityId: string; type: string; status: string; confidence: number; confidenceCategory: string; evidenceIds: string[] }>;
  contradictions: Array<{ id: string; predicate: string; explanation: string; evidenceIds: string[]; claimIds: string[] }>;
  changes: Array<{ id: string; predicate: string; changeType: string; observedAt: string; evidenceIds: string[] }>;
  leads: Array<{ id: string; seed: { type: string; value: string; label?: string }; reason: string; status: string; depth: number; discoveredByEvidenceIds: string[] }>;
  plan: { id?: string; providerIds: string[]; execution: string; automaticExpansion: false; reservations: InvestigationSummary["counts"] };
  providerAttribution: Array<{ providerId: string; provider: string; documentationUrl?: string; termsUrl?: string }>;
};
type ManagedJob = { id: string; module: string; name: string; status: string; progress: { current: number; total?: number; message?: string }; caps: { maxExternalCalls: number; timeoutMs: number }; resources: { externalCalls: number; iterations: number; wallClockMs: number }; errorCode?: string };

const TYPES = [
  ["domain", "DOMAIN"], ["ip-address", "IP ADDRESS"], ["username", "USERNAME"], ["organization", "ORGANIZATION"], ["infrastructure", "INFRASTRUCTURE"], ["hunter-event", "HUNTER EVENT"], ["passive-web", "PASSIVE WEB"], ["geographic-area", "MAP REGION"], ["authorized-exposure", "AUTHORIZED EXPOSURE"],
] as const;

function formatBytes(value: number) { if (value < 1024) return `${value} B`; if (value < 1024 ** 2) return `${(value / 1024).toFixed(1)} KiB`; return `${(value / 1024 ** 2).toFixed(1)} MiB`; }
function formatAge(value: number) { if (value < 60_000) return `${Math.max(0, Math.round(value / 1_000))} SEC`; if (value < 3_600_000) return `${Math.round(value / 60_000)} MIN`; return `${(value / 3_600_000).toFixed(1)} HR`; }
function valueText(value: unknown) { return typeof value === "string" ? value : JSON.stringify(value); }
function terminal(status: string) { return ["completed", "failed", "cancelled", "timed-out", "limit-exceeded"].includes(status); }

function seedFromDraft(draft?: HunterOsintDraft | null) {
  if (!draft) return null;
  if (draft.seed.type === "geographic-area") return { type: "geographic-area", seed: draft.seed.value, objective: draft.objective };
  return { type: "hunter-event", seed: draft.originalHunterObservation?.observationId ?? draft.seed.value, objective: draft.objective };
}

function EntityGraph({ detail }: { detail: InvestigationDetail }) {
  const nodes = detail.entities.slice(0, 60); const nodeIds = new Set(nodes.map(({ id }) => id)); const relationships = detail.relationships.filter(({ sourceEntityId, targetEntityId }) => nodeIds.has(sourceEntityId) && nodeIds.has(targetEntityId)).slice(0, 120);
  const positioned = useMemo(() => nodes.map((node, index) => { const angle = nodes.length === 1 ? 0 : index / Math.max(1, nodes.length) * Math.PI * 2 - Math.PI / 2; const ring = nodes.length < 5 ? 105 : 125 + (index % 3) * 28; return { ...node, x: 300 + Math.cos(angle) * ring, y: 190 + Math.sin(angle) * ring }; }), [nodes]);
  const byId = new Map(positioned.map((node) => [node.id, node]));
  if (!nodes.length) return <div className="osint-graph-empty"><strong>NO ENTITY GRAPH AVAILABLE</strong><p>The completed provider paths did not return graphable entities.</p></div>;
  return <div className="osint-entity-graph"><svg viewBox="0 0 600 380" role="img" aria-label={`${nodes.length} entities connected by ${relationships.length} relationships`}>
    <g className="osint-graph-links">{relationships.map((edge) => { const source = byId.get(edge.sourceEntityId); const target = byId.get(edge.targetEntityId); return source && target ? <g key={edge.id}><line x1={source.x} y1={source.y} x2={target.x} y2={target.y} /><text x={(source.x + target.x) / 2} y={(source.y + target.y) / 2}>{edge.type.slice(0, 20)}</text></g> : null; })}</g>
    <g className="osint-graph-nodes">{positioned.map((node) => <g key={node.id} transform={`translate(${node.x} ${node.y})`}><circle r={node.type === detail.investigation.seed.type ? 18 : 13} /><text y="3">{node.type.slice(0, 2).toUpperCase()}</text><title>{node.displayName} // {node.type}</title></g>)}</g>
  </svg><div className="osint-graph-legend"><span>SEED / PRIMARY</span><span>RELATED ENTITY</span><small>SHOWING {nodes.length}/{detail.entities.length} ENTITIES // {relationships.length} LINKS</small></div></div>;
}

export function OsintInvestigationPanel({ providers, hunterDraft }: { providers: Provider[]; hunterDraft?: HunterOsintDraft | null }) {
  const { notify } = useNotifications(); const draft = seedFromDraft(hunterDraft);
  const [type, setType] = useState(draft?.type ?? "domain"); const [seedSubtype, setSeedSubtype] = useState<"domain" | "ip-address" | "email-address">("domain"); const [seed, setSeed] = useState(draft?.seed ?? "");
  const [objective, setObjective] = useState(draft?.objective ?? "Collect and correlate bounded passive evidence for this exact target."); const [authorizationMode, setAuthorizationMode] = useState("public-research");
  const [authorized, setAuthorized] = useState(false); const [authorizationStatement, setAuthorizationStatement] = useState(""); const [preview, setPreview] = useState<Preview | null>(null); const [previewBusy, setPreviewBusy] = useState(false);
  const [history, setHistory] = useState<InvestigationSummary[]>([]); const [detail, setDetail] = useState<InvestigationDetail | null>(null); const [detailBusy, setDetailBusy] = useState(false); const [jobs, setJobs] = useState<ManagedJob[]>([]); const [activeRun, setActiveRun] = useState<{ jobId: string; investigationId: string } | null>(null); const [reviewBusy, setReviewBusy] = useState<string | null>(null);

  const payload = useCallback(() => ({ type, seed, seedSubtype, objective, authorizationMode, ...(type === "authorized-exposure" ? { exposureConfirmation: { confirmed: authorized, exactTarget: seed.trim(), statement: authorizationStatement } } : {}) }), [type, seed, seedSubtype, objective, authorizationMode, authorized, authorizationStatement]);
  const loadHistory = useCallback(async () => { const response = await fetch("/api/osint/investigations", { cache: "no-store" }); const data = await response.json() as { investigations?: InvestigationSummary[]; error?: string }; if (!response.ok) throw new Error(data.error ?? "Investigation history is unavailable."); setHistory(data.investigations ?? []); }, []);
  const loadDetail = useCallback(async (id: string) => { setDetailBusy(true); try { const response = await fetch(`/api/osint/investigations/${encodeURIComponent(id)}`, { cache: "no-store" }); const data = await response.json() as InvestigationDetail & { error?: string }; if (!response.ok) throw new Error(data.error ?? "Investigation detail is unavailable."); setDetail(data); } finally { setDetailBusy(false); } }, []);

  useEffect(() => { const timer = window.setTimeout(() => { void loadHistory().catch((error) => notify({ tone: "error", title: "History unavailable", message: error instanceof Error ? error.message : "Investigation history is unavailable." })); }, 0); return () => window.clearTimeout(timer); }, [loadHistory, notify]);
  useEffect(() => {
    const events = new EventSource("/api/osint/investigations/jobs/events");
    events.onmessage = (event) => { try { const data = JSON.parse(event.data) as { jobs?: ManagedJob[] }; setJobs(data.jobs ?? []); } catch { /* polling recovery below */ } };
    const poll = window.setInterval(() => void fetch("/api/osint/investigations/jobs", { cache: "no-store" }).then((response) => response.json()).then((data: { jobs?: ManagedJob[] }) => setJobs(data.jobs ?? [])).catch(() => undefined), 5_000);
    return () => { events.close(); window.clearInterval(poll); };
  }, []);
  useEffect(() => { if (!activeRun) return; const job = jobs.find(({ id }) => id === activeRun.jobId); if (!job || !terminal(job.status)) return; const timer = window.setTimeout(() => { void loadHistory(); if (job.status === "completed") void loadDetail(activeRun.investigationId); else notify({ tone: "error", title: `Investigation ${job.status}`, message: job.errorCode ?? "The managed investigation did not complete." }); setActiveRun(null); }, 0); return () => window.clearTimeout(timer); }, [jobs, activeRun, loadDetail, loadHistory, notify]);

  async function createPreview() { setPreviewBusy(true); try { const response = await fetch("/api/osint/investigations/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload()) }); const data = await response.json() as Preview & { error?: string }; if (!response.ok) throw new Error(data.error ?? "The investigation plan could not be previewed."); setPreview(data); } catch (error) { setPreview(null); notify({ tone: "error", title: "Plan held", message: error instanceof Error ? error.message : "The plan could not be previewed." }); } finally { setPreviewBusy(false); } }
  async function startInvestigation() { if (!preview?.plan) return; setPreviewBusy(true); try { const response = await fetch("/api/osint/investigations/start", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload()) }); const data = await response.json() as { jobId?: string; investigationId?: string; error?: string }; if (!response.ok || !data.jobId || !data.investigationId) throw new Error(data.error ?? "The investigation did not start."); setActiveRun({ jobId: data.jobId, investigationId: data.investigationId }); notify({ tone: "success", title: "Investigation started", message: "The approved bounded plan is running through the shared job manager." }); } catch (error) { notify({ tone: "error", title: "Investigation held", message: error instanceof Error ? error.message : "The investigation did not start." }); } finally { setPreviewBusy(false); } }
  async function cancelJob(id: string) { const response = await fetch(`/api/osint/investigations/jobs/${encodeURIComponent(id)}`, { method: "DELETE" }); if (!response.ok) notify({ tone: "error", title: "Cancellation held", message: "The investigation job could not be cancelled." }); }
  async function reviewLead(id: string, status: "approved" | "rejected") { if (!detail) return; setReviewBusy(id); try { const response = await fetch(`/api/osint/investigations/${encodeURIComponent(detail.investigation.id)}/leads/${encodeURIComponent(id)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "The lead decision was not saved."); await loadDetail(detail.investigation.id); notify({ tone: "success", title: `Candidate ${status}`, message: "The review was saved. No provider request or automatic expansion was started." }); } catch (error) { notify({ tone: "error", title: "Review not saved", message: error instanceof Error ? error.message : "The lead decision was not saved." }); } finally { setReviewBusy(null); } }
  async function exportReport() { if (!detail) return; const response = await fetch(`/api/osint/investigations/${encodeURIComponent(detail.investigation.id)}/report`); const data = await response.json() as { filename?: string; content?: string; mimeType?: string; error?: string }; if (!response.ok || !data.content) { notify({ tone: "error", title: "Export unavailable", message: data.error ?? "The report could not be generated." }); return; } const url = URL.createObjectURL(new Blob([data.content], { type: data.mimeType ?? "text/markdown" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = data.filename ?? "voidcat-osint-report.md"; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1_000); }

  const activeJobs = jobs.filter(({ status }) => !terminal(status)); const providerById = new Map(providers.map((provider) => [provider.id, provider])); const conclusions = new Map(detail?.conclusions.map((item) => [item.claimId, item]) ?? []);
  return <section className="osint-investigation-workspace">
    <aside className="osint-investigation-history"><header><span>INVESTIGATION ARCHIVE</span><b>{history.length} RECORDS</b></header><div>{history.length ? history.map((item) => <button className={detail?.investigation.id === item.id ? "selected" : ""} key={item.id} onClick={() => void loadDetail(item.id)}><span>{item.status.toUpperCase()} // {new Date(item.updatedAt).toLocaleDateString()}</span><strong>{item.seed.label ?? item.seed.value}</strong><small>{item.seed.type.toUpperCase()} // {item.counts.entities} ENTITIES // {formatBytes(item.counts.evidenceBytes)}</small>{item.warnings.length > 0 && <em>{item.warnings.length} WARNING(S)</em>}</button>) : <p>NO SAVED INVESTIGATIONS</p>}</div></aside>
    <main className="osint-investigation-main">
      <section className="osint-investigation-builder">
        <header><div><span>NEW BOUNDED INVESTIGATION</span><strong>PLAN BEFORE EXECUTION</strong></div><b>PASSIVE ONLY // DEPTH 1</b></header>
        <div className="osint-seed-controls"><label><span>INVESTIGATION TYPE</span><select value={type} onChange={(event) => { const next = event.currentTarget.value; setType(next); setAuthorizationMode(next === "authorized-exposure" ? "exposure-check" : authorizationMode === "exposure-check" ? "public-research" : authorizationMode); setPreview(null); }}>{TYPES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{["infrastructure", "authorized-exposure"].includes(type) && <label><span>SEED KIND</span><select value={seedSubtype} onChange={(event) => setSeedSubtype(event.currentTarget.value as typeof seedSubtype)}>{type === "infrastructure" ? <><option value="domain">DOMAIN</option><option value="ip-address">IP ADDRESS</option></> : <><option value="email-address">EMAIL ADDRESS</option><option value="domain">VERIFIED DOMAIN</option></>}</select></label>}<label className="wide"><span>EXACT SEED</span><input value={seed} onChange={(event) => { setSeed(event.currentTarget.value); setPreview(null); }} placeholder={type === "geographic-area" ? "south, west, north, east" : type === "hunter-event" ? "Hunter observation ID" : "Exact target"} /></label><label><span>AUTHORIZATION MODE</span><select disabled={type === "authorized-exposure"} value={authorizationMode} onChange={(event) => { setAuthorizationMode(event.currentTarget.value); setPreview(null); }}><option value="public-research">PUBLIC RESEARCH</option><option value="owned-asset">OWNED ASSET</option><option value="authorized-client">AUTHORIZED CLIENT</option>{type === "authorized-exposure" && <option value="exposure-check">EXPOSURE CHECK</option>}</select></label><label className="objective"><span>OBJECTIVE</span><textarea value={objective} onChange={(event) => { setObjective(event.currentTarget.value); setPreview(null); }} /></label></div>
        {type === "authorized-exposure" && <div className="osint-sensitive-authorization"><strong>SENSITIVE EXPOSURE MODE</strong><label><input type="checkbox" checked={authorized} onChange={(event) => { setAuthorized(event.currentTarget.checked); setPreview(null); }} />I AM AUTHORIZED TO CHECK THIS EXACT TARGET</label><textarea value={authorizationStatement} onChange={(event) => { setAuthorizationStatement(event.currentTarget.value); setPreview(null); }} placeholder="State the authorization for this exact target." /><small>EXACT TARGET ONLY // NO DISCOVERED-ADDRESS EXPANSION // NO AUTOMATIC HUNTER FORWARDING</small></div>}
        <div className="osint-builder-actions"><button onClick={() => void createPreview()} disabled={previewBusy || !seed.trim() || !objective.trim()}>{previewBusy ? "CALCULATING..." : "PREVIEW BUDGET & PLAN"}</button><button className="primary" onClick={() => void startInvestigation()} disabled={!preview?.plan || preview.policyDecision.outcome !== "allow" || previewBusy || Boolean(activeRun)}>START APPROVED PLAN</button></div>
      </section>
      {preview && <section className={`osint-plan-preview ${preview.sensitive ? "sensitive" : ""}`}><header><div><span>PRE-EXECUTION REVIEW // {preview.policyDecision.outcome.toUpperCase()}</span><strong>{preview.plan?.id ?? "POLICY HOLD"}</strong></div><b>{preview.providerIds.length} FIXED PROVIDER PATH(S)</b></header><div className="osint-budget-grid"><article><span>PROVIDERS</span><strong>{preview.plan?.reservations.providers ?? 0} / {preview.budget.maximumProviders}</strong></article><article><span>EXTERNAL CALLS</span><strong>{preview.plan?.reservations.externalCalls ?? 0} / {preview.budget.maximumExternalCalls}</strong></article><article><span>RUNTIME</span><strong>{Math.round(preview.budget.maximumRuntimeMs / 1_000)} SEC</strong></article><article><span>ENTITIES</span><strong>{preview.plan?.reservations.maximumEntities ?? 0} / {preview.budget.maximumEntities}</strong></article><article><span>EVIDENCE</span><strong>{formatBytes(preview.plan?.reservations.maximumEvidenceBytes ?? 0)}</strong></article><article><span>DEPTH</span><strong>{preview.budget.maximumDiscoveryDepth}</strong></article></div><div className="osint-plan-steps">{preview.providerIds.map((id, index) => { const provider = providerById.get(id); const ready = provider?.runtime.configured; return <article key={id}><i>{String(index + 1).padStart(2, "0")}</i><div><strong>{provider?.displayName ?? id}</strong><small>{preview.plan?.steps.find((step) => step.providerId === id)?.capabilityId ?? "NO COMPATIBLE STEP"}</small></div><b className={ready ? "ready" : "held"}>{ready ? provider?.runtime.lastStatus.toUpperCase() : "NOT CONFIGURED"}</b></article>; })}</div>{preview.warnings.map((warning) => <p key={warning}>WARNING // {warning}</p>)}</section>}
      {activeJobs.length > 0 && <section className="osint-investigation-jobs"><header><span>LIVE JOB CONTROL</span><b>{activeJobs.length} ACTIVE</b></header>{activeJobs.map((job) => { const progress = job.progress.total ? Math.round(job.progress.current / job.progress.total * 100) : 0; return <article key={job.id}><strong>{job.status.toUpperCase()}</strong><div><b>{job.progress.message ?? "AWAITING PROGRESS"}</b><small>CALLS {job.resources.externalCalls}/{job.caps.maxExternalCalls} // {formatAge(job.resources.wallClockMs)}</small><i style={{ "--osint-investigation-progress": `${progress}%` } as CSSProperties} /></div><button onClick={() => void cancelJob(job.id)}>CANCEL</button></article>; })}</section>}
      {detailBusy && <div className="osint-detail-loading">RETRIEVING INVESTIGATION GRAPH...</div>}
      {detail && !detailBusy && <section className="osint-investigation-detail">
        <header><div><span>{detail.investigation.status.toUpperCase()} // {detail.investigation.id}</span><h3>{detail.investigation.seed.label ?? detail.investigation.seed.value}</h3><p>{detail.investigation.objective}</p></div><button onClick={() => void exportReport()}>EXPORT CITED REPORT</button></header>
        {(detail.investigation.warnings.length > 0 || detail.evidence.some(({ sensitivity }) => sensitivity !== "public") || detail.investigation.status !== "completed") && <div className="osint-investigation-warning"><strong>{detail.evidence.some(({ sensitivity }) => sensitivity !== "public") ? "SENSITIVE OR RESTRICTED FINDINGS" : "INCOMPLETE FINDINGS"}</strong>{detail.investigation.warnings.map((warning) => <p key={warning}>{warning}</p>)}<small>VERIFY PRIMARY SOURCES BEFORE ACTING // ABSENCE OF EVIDENCE IS NOT EVIDENCE OF ABSENCE</small></div>}
        <div className="osint-detail-grid"><section className="osint-graph-card"><header><span>ENTITY / RELATIONSHIP GRAPH</span><b>{detail.entities.length} NODES // {detail.relationships.length} LINKS</b></header><EntityGraph detail={detail} /></section><section className="osint-provider-attribution"><header><span>PLAN & PROVIDER STATUS</span><b>{detail.plan.execution.toUpperCase()}</b></header>{detail.providerAttribution.map((item) => { const runtime = providerById.get(item.providerId)?.runtime; return <article key={item.providerId}><div><strong>{item.provider}</strong><small>{item.providerId.toUpperCase()} // {runtime?.configured ? runtime.lastStatus.toUpperCase() : "HISTORICAL / CURRENTLY UNAVAILABLE"}</small></div>{item.documentationUrl && <a href={item.documentationUrl} target="_blank" rel="noreferrer">ATTRIBUTION ↗</a>}</article>; })}</section></div>
        <section className="osint-claims-panel"><header><span>CLAIMS / CONFIDENCE</span><b>{detail.claims.length} CLAIMS // {detail.contradictions.length} CONTRADICTIONS</b></header>{detail.claims.length ? detail.claims.map((claim) => { const conclusion = conclusions.get(claim.id); return <article className={`status-${claim.status}`} key={claim.id}><div><span>{claim.status.toUpperCase()} // {claim.confidenceCategory.toUpperCase()}</span><strong>{claim.predicate}: {valueText(claim.value)}</strong><p>{conclusion?.confidence.explanation ?? claim.explanation}</p><small>SUPPORT {claim.evidenceIds.map((id) => `[EV:${id}]`).join(" ") || "NONE"}</small>{conclusion?.contradictingEvidenceIds.length ? <small className="contradiction">CONTRADICTS {conclusion.contradictingEvidenceIds.map((id) => `[EV:${id}]`).join(" ")}</small> : null}</div><b>{Math.round(claim.confidence * 100)}%</b></article>; }) : <p>NO EVIDENCE-BACKED CLAIMS WERE PRODUCED.</p>}{detail.contradictions.map((item) => <article className="contradiction-record" key={item.id}><div><span>EXPLICIT CONTRADICTION</span><strong>{item.predicate}</strong><p>{item.explanation}</p><small>{item.evidenceIds.map((id) => `[EV:${id}]`).join(" ")}</small></div></article>)}</section>
        <section className="osint-evidence-panel"><header><span>EVIDENCE INDEX</span><b>{detail.evidence.length} RECORDS // {formatBytes(detail.evidence.reduce((sum, item) => sum + item.byteLength, 0))}</b></header>{detail.evidence.map((item) => <article key={item.id}><header><span>{item.sensitivity.toUpperCase()} // {item.cache.status.toUpperCase()} // AGE {formatAge(item.cache.ageMs)}</span><b>[EV:{item.id}]</b></header><strong>{item.title}</strong><p>{item.excerpt ?? "No bounded excerpt was retained."}</p><footer><small>{item.attribution.provider ?? item.providerId} // RETRIEVED {new Date(item.retrievedAt).toLocaleString()}</small>{item.url && <a href={item.url} target="_blank" rel="noreferrer">OPEN SOURCE ↗</a>}</footer></article>)}</section>
        <section className="osint-lead-approval"><header><span>CANDIDATE-LEAD REVIEW</span><b>NO AUTOMATIC EXPANSION</b></header>{detail.leads.length ? detail.leads.map((lead) => <article key={lead.id}><div><span>{lead.status.toUpperCase()} // DEPTH {lead.depth}</span><strong>{lead.seed.label ?? lead.seed.value}</strong><p>{lead.reason}</p><small>{lead.discoveredByEvidenceIds.map((id) => `[EV:${id}]`).join(" ")}</small></div><div><button disabled={reviewBusy === lead.id || lead.status === "approved"} onClick={() => void reviewLead(lead.id, "approved")}>APPROVE CANDIDATE</button><button className="reject" disabled={reviewBusy === lead.id || lead.status === "rejected"} onClick={() => void reviewLead(lead.id, "rejected")}>REJECT</button></div></article>) : <p>NO CANDIDATE LEADS.</p>}</section>
      </section>}
    </main>
  </section>;
}
