/*
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy at
 * https://opensource.org/license/cpal-1.0. The Original Code is VoidCat Harness. The Initial Developer is
 * iamnotnotacat. Copyright (c) 2026 iamnotnotacat. All Rights Reserved. Software is provided "AS IS",
 * without warranty. See LICENSE and NOTICE for details and attribution requirements.
 */
"use client";

import { useEffect, useState } from "react";
import type { Profile } from "./PhaseThreePanels";
import { useNotifications } from "./NotificationCenter";

type HfModel = { id: string; author: string; downloads: number; likes: number; lastModified: string | null; tags: string[] };
type HfBundle = { id: string; label: string; files: string[]; sizeBytes: number; fileCount: number };
type DownloadJob = { id: string; name: string; status: string; progress: { current: number; total?: number; message?: string }; errorCode?: string };
type OllamaModel = { name?: string; model?: string; size?: number; modified_at?: string; details?: { parameter_size?: string; quantization_level?: string } };

export function UnitSettingsPanel({ profile, contextLength, onContextChange, onSaveProfile, onRescan }: { profile?: Profile; contextLength: number; onContextChange: (value: number) => void; onSaveProfile: (value: Partial<Profile> & { id: string }) => Promise<void>; onRescan: () => Promise<void> }) {
  const { notify } = useNotifications(); const [temperature, setTemperature] = useState(profile?.temperature ?? .7); const [topP, setTopP] = useState(profile?.topP ?? .95); const [repeatPenalty, setRepeatPenalty] = useState(profile?.repeatPenalty ?? 1.05); const [maxTokens, setMaxTokens] = useState(profile?.maxTokens ?? 2048); const [query, setQuery] = useState(""); const [hfModels, setHfModels] = useState<HfModel[]>([]); const [selectedRepository, setSelectedRepository] = useState(""); const [hfBundles, setHfBundles] = useState<HfBundle[]>([]); const [ollamaName, setOllamaName] = useState(""); const [ollama, setOllama] = useState<{ available: boolean; models: OllamaModel[] }>({ available: false, models: [] }); const [jobs, setJobs] = useState<DownloadJob[]>([]); const [busy, setBusy] = useState("");
  useEffect(() => { const refresh = () => { void fetch("/api/models/downloads").then((response) => response.json()).then((data: { jobs?: DownloadJob[] }) => setJobs(data.jobs ?? [])); }; refresh(); const timer = window.setInterval(refresh, 1200); void fetch("/api/models/ollama").then((response) => response.json()).then(setOllama); return () => window.clearInterval(timer); }, []);
  async function saveSampling() { if (!profile) return; await onSaveProfile({ id: profile.id, temperature, topP, repeatPenalty, maxTokens }); notify({ tone: "success", title: "UNIT profile updated", message: "Sampling and response limits will apply to the next Command transmission." }); }
  async function search() { if (query.trim().length < 2 || busy) return; setBusy("search"); try { const response = await fetch("/api/models/search/huggingface", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query }) }); const data = await response.json() as { results?: HfModel[]; error?: string }; if (!response.ok) throw new Error(data.error ?? "Search failed."); setHfModels(data.results ?? []); } catch (error) { notify({ tone: "error", title: "Hugging Face search failed", message: error instanceof Error ? error.message : "Search failed." }); } finally { setBusy(""); } }
  async function showFiles(repository: string) { setBusy(`files:${repository}`); try { const response = await fetch("/api/models/files/huggingface", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ repository }) }); const data = await response.json() as { bundles?: HfBundle[]; error?: string }; if (!response.ok) throw new Error(data.error ?? "GGUF file discovery failed."); setSelectedRepository(repository); setHfBundles(data.bundles ?? []); } finally { setBusy(""); } }
  async function download(kind: "huggingface" | "ollama", name: string, files: string[] = []) { if (!window.confirm(`Download ${name}? Model files can consume many gigabytes. VoidCat requires 10 GB of free disk headroom and the download can be cancelled.`)) return; const response = await fetch("/api/models/downloads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, name, files }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "Download could not start."); notify({ tone: "success", title: "Download queued", message: `${name} is managed by VoidCat's bounded job system.` }); }
  const estimateTokens = Math.ceil(maxTokens + contextLength * .05);
  return <section className="phase-panel unit-settings-panel"><div className="phase-heading"><div><p className="kicker">UNIT BEHAVIOR {"//"} MODEL ACQUISITION</p><h2>UNIT SETTINGS</h2></div><span className="phase-counter">LOCAL RUNTIME</span></div><div className="unit-settings-layout">
    <article><header><span>ACTIVE PROFILE SAMPLING</span><b>{profile?.name ?? "NO PROFILE"}</b></header><div className="sampling-grid"><label>TEMPERATURE<input type="range" min="0" max="2" step="0.05" value={temperature} onChange={(event) => setTemperature(Number(event.target.value))} /><strong>{temperature.toFixed(2)}</strong></label><label>TOP P<input type="range" min="0.05" max="1" step="0.05" value={topP} onChange={(event) => setTopP(Number(event.target.value))} /><strong>{topP.toFixed(2)}</strong></label><label>REPEAT PENALTY<input type="range" min="0.8" max="2" step="0.05" value={repeatPenalty} onChange={(event) => setRepeatPenalty(Number(event.target.value))} /><strong>{repeatPenalty.toFixed(2)}</strong></label><label>MAX RESPONSE TOKENS<input type="number" min="128" max="16384" step="128" value={maxTokens} onChange={(event) => setMaxTokens(Number(event.target.value))} /></label><label>CONTEXT WINDOW<select value={contextLength} onChange={(event) => onContextChange(Number(event.target.value))}><option value={4096}>4,096</option><option value={8192}>8,192</option><option value={16384}>16,384</option><option value={32768}>32,768</option></select></label></div><button className="primary-action" onClick={() => void saveSampling()} disabled={!profile}>SAVE UNIT PROFILE</button><p>Token estimate reserves approximately {estimateTokens.toLocaleString()} positions for response and system/tool boundaries. Actual tokenization depends on the loaded UNIT.</p></article>
    <article className="model-acquisition"><header><span>HUGGING FACE // GGUF</span><a href="https://huggingface.co/models?library=gguf" target="_blank" rel="noreferrer">OPEN HUB ↗</a></header><div className="model-search"><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === "Enter" && void search()} placeholder="Search official Hub API" /><button onClick={() => void search()}>{busy === "search" ? "SEARCHING..." : "SEARCH"}</button></div><div className="download-model-list">{hfModels.map((model) => <div key={model.id}><span><strong>{model.id}</strong><small>{model.downloads.toLocaleString()} DOWNLOADS // {model.likes} LIKES</small></span><button onClick={() => void showFiles(model.id).catch((error) => notify({ tone: "error", title: "File discovery failed", message: error.message }))}>{busy === `files:${model.id}` ? "READING..." : "CHOOSE GGUF"}</button></div>)}</div>{selectedRepository && <div className="hf-file-bundles"><header><span>{selectedRepository}</span><b>{hfBundles.length} OPTIONS</b></header>{hfBundles.map((bundle) => <div key={bundle.id}><span><strong>{bundle.label}</strong><small>{bundle.fileCount} FILE{bundle.fileCount === 1 ? "" : "S"} // {(bundle.sizeBytes / 1024 ** 3).toFixed(2)} GB</small></span><button onClick={() => void download("huggingface", selectedRepository, bundle.files).catch((error) => notify({ tone: "error", title: "Download failed", message: error.message }))}>DOWNLOAD</button></div>)}</div>}<p>Search and file discovery occur only when requested. Exact GGUF files or complete shard bundles download into the primary model folder selected in App Settings and appear in the Unit Bank after completion.</p></article>
    <article className="model-acquisition"><header><span>OLLAMA LIBRARY</span><a href="https://ollama.com/search" target="_blank" rel="noreferrer">BROWSE LIBRARY ↗</a></header><div className="model-search"><input value={ollamaName} onChange={(event) => setOllamaName(event.target.value)} placeholder="Exact model:tag" /><button onClick={() => void download("ollama", ollamaName).catch((error) => notify({ tone: "error", title: "Ollama pull failed", message: error.message }))} disabled={!ollamaName.trim() || !ollama.available}>PULL MODEL</button></div><p>{ollama.available ? `${ollama.models.length} Ollama model(s) installed. Ollama keeps these in its own runtime library.` : "Ollama is not running at localhost:11434. Start Ollama before pulling."}</p>{ollama.models.slice(0, 20).map((model) => <div className="ollama-installed" key={model.model ?? model.name}><strong>{model.model ?? model.name}</strong><span>{model.details?.parameter_size ?? "?"} // {model.details?.quantization_level ?? "?"} // {model.size ? `${(model.size / 1024 ** 3).toFixed(2)} GB` : "SIZE UNKNOWN"}</span></div>)}</article>
    <article className="download-jobs"><header><span>DOWNLOAD JOBS</span><button onClick={() => void onRescan()}>RESCAN UNIT BANK</button></header>{jobs.length ? jobs.map((job) => { const progress = job.progress.total ? Math.round(job.progress.current / job.progress.total * 100) : 0; const active = job.status === "queued" || job.status === "running"; return <div key={job.id}><span><strong>{job.name}</strong><small>{job.status.toUpperCase()} // {job.progress.message ?? "WAITING"}</small><i><b style={{ width: `${progress}%` }} /></i></span>{active && <button onClick={() => void fetch(`/api/models/downloads/${job.id}`, { method: "DELETE" })}>CANCEL</button>}</div>; }) : <p>No active or recent download jobs.</p>}</article>
  </div></section>;
}
